import Model from 'ember-data/model';
import attr from 'ember-data/attr';

export default Model.extend({
  nombreCompleto: attr(),
  siglas: attr(),
  estado: attr(),
  secretarioGeneral: attr(),
  secretarioGeneralEnFunciones: attr(),
  logoURL: attr(),
  lema: attr(),
  fundacion: attr(),
  telefono: attr(),
  direccion: attr(),
  paginaWeb: attr(),
  correo: attr(),
  facebook: attr(),
  twitter: attr(),
  historia: attr(),
  principios: attr(),
  procedimientosDenuncia: attr(),
  procedimientosURL: attr(),
  programaURL: attr(),
  escrituraURL: attr(),
  estatutosURL: attr(),
  eticaURL: attr(),
  procedimientosTransparenciaURL: attr(),
  fuenteTexto: attr(),
  fuenteURL: attr(),
  procedimientosAfiliacion: attr(),
});
